### ISSUE TITLE
ID RSA . pub

### ISSUE THREAD

**Issue by sebastien-tetaud** [esa-cdab/cdab-testsuite#10]
Hello, 

your id_rsa is visible publicly on the repository. It might have some security issue for your jetkins.  

https://github.com/esacdab/cdab-testsuite/blob/main/src/docker/id_rsa.pub

Kind regards,
Sebastien

**Comment by esa-cdab** [comment]
Thank you Sebatien.
the id_rsa are just example used in the internal hosts, so no publicy exposed.
Best regards,
  CDAB team
